# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-23 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='url',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='时间索引url'),
        ),
    ]
